version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: next-auth-postgres
    restart: always
    ports:
      - '${POSTGRES_PORT:-5443}:5432'
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-next_auth_db}
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
