services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: ai-backend-api
    restart: unless-stopped
    ports:
      - "${DOCKER_API_PORT}:${API_PORT}"
    env_file:
      - .env
    environment:
      MONGODB_URL: ${DOCKER_MONGODB_URL}
      DATABASE_NAME: ${DATABASE_NAME}
      REDIS_URL: ${DOCKER_REDIS_URL}
    depends_on:
      - mongodb
      - redis
    networks:
      - ai-backend-network

  mongodb:
    image: mongo:7.0
    container_name: ai-backend-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: ai_backend
    volumes:
      - mongodb_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - ai-backend-network

  redis:
    image: redis:7.2-alpine
    container_name: ai-backend-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - ai-backend-network

  celery-worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    container_name: ai-backend-celery
    restart: unless-stopped
    command: ["python", "celery_worker.py"]
    env_file:
      - .env
    environment:
      MONGODB_URL: ${DOCKER_MONGODB_URL}
      DATABASE_NAME: ${DATABASE_NAME}
      REDIS_URL: ${DOCKER_REDIS_URL}
    depends_on:
      - mongodb
      - redis
    networks:
      - ai-backend-network

  mongo-express:
    image: mongo-express
    container_name: ai-backend-mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password123
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_URL: mongodb://admin:password123@mongodb:27017/?authSource=admin
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: password123
    depends_on:
      - mongodb
    networks:
      - ai-backend-network

  # Optional: MinIO for S3-compatible storage
  minio:
    image: minio/minio:latest
    container_name: ai-backend-minio
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - ai-backend-network

volumes:
  mongodb_data:
  redis_data:
  minio_data:

networks:
  ai-backend-network:
    driver: bridge
